language: c
compiler: gcc
sudo: required
dist: xenial
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  - sudo apt update
  - sudo apt install -y cmake valac libgtk-3-dev libgee-0.8-dev libclutter-gtk-1.0-dev libclutter-1.0-dev libclutter-gst-3.0-dev libwebkit2gtk-4.0-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
